### ISSUE TITLE
Return "p" values

### ISSUE THREAD

**Issue by dauntaun** [leonardblaschek/tukeygrps#2]
It would be nice if the function also returned the numeric p-values as a separate column for us to compare the most significant differences.

**Comment by dauntaun** [comment]
Never mind, forgot that it would have to include all possible combinations which would not fit the original dataframe.

**Comment by leonardblaschek** [comment]
In addition "most significant" is not really a healthy statistical concept in my opinion. If the p-value allows you to reject the null hypothesis based on your _a priori_ set alpha, the more relevant metric to compare different groups becomes the effect size, _i.e_ the difference of the means.

That aside, I think the option to output an additional data frame of all the pairwise p-values is a good idea.
